name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi @${{ github.actor }}! Thank you for opening this issue. We appreciate your contribution and will look into it shortly. 😊"
        pr-message: "Thank you @${{ github.actor }} for submitting your pull request! We will review it as soon as possible. Your contributions are valued! 🙌"
